import type { Backlink, EmlData, HistorySnapshot, NoteFile } from './types';

export const files: NoteFile[] = [
  { id: 'api', title: 'API Design Guidelines', file: 'api-design.md', type: 'md', folder: 'Engineering', pinned: true },
  { id: 'errors', title: 'Error Catalog', file: 'error-catalog.md', type: 'md', folder: 'Engineering', parent: 'api', pinned: false },
  { id: 'runbook', title: 'Deployment Runbook', file: 'deployment.md', type: 'md', folder: 'Engineering', pinned: false },
  { id: 'security', title: 'Security Checklist', file: 'security.md', type: 'md', folder: 'Engineering', pinned: false },
  { id: 'oncall', title: 'On-call Playbook', file: 'oncall.md', type: 'md', folder: 'Engineering', pinned: false },
  { id: 'adr', title: 'ADR-014 Event Bus', file: 'adr-014.md', type: 'md', folder: 'Engineering', pinned: false },
  { id: 'roadmap', title: 'Roadmap Q3', file: 'roadmap.md', type: 'md', folder: 'Product', pinned: true },
  { id: 'milestones', title: 'Q3 Milestones', file: 'q3-milestones.md', type: 'md', folder: 'Product', parent: 'roadmap', pinned: false },
  { id: 'landing', title: 'Landing Page', file: 'landing-page.html', type: 'html', folder: 'Web', pinned: true },
  { id: 'pricing', title: 'Pricing Page', file: 'pricing.html', type: 'html', folder: 'Web', pinned: false },
  { id: 'signature', title: 'Email Signature', file: 'signature.html', type: 'html', folder: 'Web', pinned: false },
  { id: 'q2', title: 'Q2 Status Report', file: 'q2-status.eml', type: 'eml', folder: 'Reports', pinned: true },
  { id: 'postmortem', title: 'Incident #284 Postmortem', file: 'postmortem-284.md', type: 'md', folder: 'Reports', pinned: false },
  { id: 'digest', title: 'Weekly Digest', file: 'weekly-digest.eml', type: 'eml', folder: 'Reports', pinned: false },
  { id: 'welcome', title: 'Welcome Email', file: 'welcome.eml', type: 'eml', folder: 'Reports', pinned: false },
];

export const folderOrder = ['Engineering', 'Product', 'Web', 'Reports', 'Notes', 'Daily'];

export const sources: Record<string, string> = {
  api: [
    '---', 'tags: [api, guidelines, platform]', 'status: living', '---',
    '# API Design Guidelines', '',
    '## Versioning',
    'All public endpoints are versioned via the URL path. Breaking changes require a new major version — see [[Deprecation Policy]] before removing fields.', '',
    '```http', 'GET /api/v2/users/:id', 'Accept: application/json', '```', '',
    '## Conventions',
    '- Use plural, lowercase resource names (`/invoices`)',
    '- Return ISO-8601 timestamps in UTC',
    '- Paginate with `cursor`, never offset', '',
    '## Error Format',
    'Errors return a consistent envelope with `code`, `message`, and an optional `details` array. See [[Error Catalog]] for the full list.',
  ].join('\n'),
  runbook: [
    '---', 'tags: [ops, deploy]', '---',
    '# Deployment Runbook', '',
    'Step-by-step rollout for the staging → prod promotion pipeline. Follows the [[API Design Guidelines]] for versioned releases.', '',
    '## Pre-flight',
    '- [x] Confirm green CI on `main`',
    '- [x] Tag the release `vX.Y.Z`',
    '- [ ] Notify #releases channel', '',
    '## Promote',
    '1. Deploy to staging',
    '2. Run smoke suite',
    '3. Canary 10% then 100%',
  ].join('\n'),
  adr: [
    '---', 'tags: [architecture, decision]', '---',
    '# ADR-014 · Event Bus', '',
    '**Status:** Accepted', '',
    '## Decision',
    'Adopt an internal event bus over point-to-point calls. Per the [[API Design Guidelines]], v2 endpoints publish domain events asynchronously.', '',
    '## Flow',
    '```mermaid',
    'graph LR',
    '  P[Producer] --> B((Event Bus))',
    '  B --> C1[Consumer A]',
    '  B --> C2[Consumer B]',
    '```',
    'At steady state, throughput per partition follows $T = \\lambda / \\mu$.', '',
    '## Consequences',
    '- Looser coupling between services',
    '- Requires an idempotency strategy',
  ].join('\n'),
  landing: [
    '<!doctype html>',
    '<html><head><meta charset="utf-8"><title>Acme Cloud</title></head>',
    '<body style="margin:0;font-family:-apple-system,system-ui,sans-serif;color:#1d1d1f">',
    '  <header style="padding:64px 40px;text-align:center;background:#faf8f3">',
    '    <h1 style="font-size:40px;margin:0 0 12px;letter-spacing:-.02em">Ship faster on Acme Cloud</h1>',
    '    <p style="font-size:18px;color:#6e6e73;margin:0 0 26px">Deploy in seconds. Scale without thinking.</p>',
    '    <a href="#" style="display:inline-block;padding:13px 30px;background:#26241f;color:#fff;border-radius:9px;text-decoration:none;font-weight:600">Get started</a>',
    '  </header>',
    '  <section style="padding:54px 40px;display:flex;gap:28px;max-width:900px;margin:0 auto">',
    '    <div style="flex:1"><h3 style="margin:0 0 6px">Fast</h3><p style="color:#6e6e73;margin:0">Edge deploys worldwide.</p></div>',
    '    <div style="flex:1"><h3 style="margin:0 0 6px">Simple</h3><p style="color:#6e6e73;margin:0">One command to ship.</p></div>',
    '    <div style="flex:1"><h3 style="margin:0 0 6px">Secure</h3><p style="color:#6e6e73;margin:0">SOC 2 by default.</p></div>',
    '  </section>',
    '</body></html>',
  ].join('\n'),
  signature: [
    '<!doctype html>',
    '<html><body style="margin:0;font-family:-apple-system,system-ui,sans-serif">',
    '  <table style="font-size:13px;color:#1d1d1f"><tr>',
    '    <td style="padding-right:14px;border-right:2px solid #c9b89a">',
    '      <div style="font-weight:700;font-size:15px">Jordan Lee</div>',
    '      <div style="color:#6e6e73">Staff Engineer · Acme</div>',
    '    </td>',
    '    <td style="padding-left:14px;color:#6e6e73;font-size:12px">jordan@acme.dev<br>acme.dev</td>',
    '  </tr></table>',
    '</body></html>',
  ].join('\n'),
  security: [
    '---', 'tags: [security, checklist, platform]', 'status: living', '---',
    '# Security Checklist', '',
    'Run before every production release. Pairs with the [[Deployment Runbook]].', '',
    '## Authentication',
    '- [x] All endpoints require a scoped token',
    '- [x] Tokens expire after 24h',
    '- [ ] Rotate signing keys quarterly', '',
    '## Data',
    '- [x] PII encrypted at rest (AES-256)',
    '- [ ] Audit log retention set to 90 days', '',
    '## Dependencies',
    '- [ ] `npm audit` clean on `main`',
    '- [ ] No critical CVEs in base images',
  ].join('\n'),
  oncall: [
    '---', 'tags: [ops, oncall]', '---',
    '# On-call Playbook', '',
    'First responder guide for the platform rotation. Escalate to the [[Deployment Runbook]] owner for rollbacks.', '',
    '## Severity Levels',
    '- **SEV1** — respond in 5 min · page on-call',
    '- **SEV2** — respond in 30 min · page on-call',
    '- **SEV3** — next business day · no page', '',
    '## First 10 Minutes',
    '1. Acknowledge the alert',
    '2. Open the incident channel',
    '3. Check the [[API Design Guidelines]] status dashboard',
    '4. Decide: mitigate or roll back',
  ].join('\n'),
  roadmap: [
    '---', 'tags: [product, roadmap]', 'status: draft', '---',
    '# Roadmap · Q3', '',
    '> North star: make multi-region the default.', '',
    '## Now',
    '- Multi-region failover (depends on [[ADR-014 Event Bus]])',
    '- Deprecate v1 endpoints', '',
    '## Next',
    '- Self-serve usage dashboards',
    '- Regional data residency controls', '',
    '## Later',
    '- Edge function runtime',
    '- Bring-your-own-key encryption',
  ].join('\n'),
  postmortem: [
    '---', 'tags: [incident, postmortem]', '---',
    '# Incident #284 · Postmortem', '',
    '**Status:** Resolved · **Duration:** 41 min · **Impact:** elevated 5xx on the API gateway', '',
    '## Timeline',
    '- `14:02` — error rate alert fires',
    '- `14:09` — bad config identified',
    '- `14:31` — rollback complete',
    '- `14:43` — metrics nominal', '',
    '## Root Cause',
    'A malformed rate-limit rule shipped without passing the [[Security Checklist]] gate.', '',
    '## Action Items',
    '- [ ] Add config schema validation to CI',
    '- [ ] Require checklist sign-off on gateway changes',
  ].join('\n'),
  pricing: [
    '<!doctype html>',
    '<html><head><meta charset="utf-8"><title>Pricing</title></head>',
    '<body style="margin:0;font-family:-apple-system,system-ui,sans-serif;color:#1d1d1f;background:#fff">',
    '  <section style="padding:56px 40px;text-align:center">',
    '    <h1 style="font-size:34px;margin:0 0 8px;letter-spacing:-.02em">Simple, usage-based pricing</h1>',
    '    <p style="font-size:16px;color:#6e6e73;margin:0">Only pay for what you deploy.</p>',
    '  </section>',
    '  <section style="display:flex;gap:20px;max-width:880px;margin:0 auto 60px;padding:0 40px">',
    '    <div style="flex:1;border:1px solid #e7e3da;border-radius:14px;padding:28px"><div style="font-weight:700;font-size:15px">Hobby</div><div style="font-size:32px;font-weight:700;margin:10px 0">$0</div><p style="color:#6e6e73;font-size:13px;margin:0">1 project · community support</p></div>',
    '    <div style="flex:1;border:2px solid #26241f;border-radius:14px;padding:28px"><div style="font-weight:700;font-size:15px">Pro</div><div style="font-size:32px;font-weight:700;margin:10px 0">$20<span style="font-size:14px;color:#6e6e73">/mo</span></div><p style="color:#6e6e73;font-size:13px;margin:0">Unlimited projects · SLAs</p></div>',
    '    <div style="flex:1;border:1px solid #e7e3da;border-radius:14px;padding:28px"><div style="font-weight:700;font-size:15px">Enterprise</div><div style="font-size:32px;font-weight:700;margin:10px 0">Custom</div><p style="color:#6e6e73;font-size:13px;margin:0">SSO · dedicated support</p></div>',
    '  </section>',
    '</body></html>',
  ].join('\n'),
  errors: [
    '---', 'tags: [api, reference]', '---',
    '# Error Catalog', '',
    'Canonical list of error codes returned by the v2 API. Part of the [[API Design Guidelines]].', '',
    '## Client Errors',
    '- `invalid_request` — malformed or missing parameters',
    '- `unauthorized` — missing or expired token',
    '- `forbidden` — token lacks the required scope',
    '- `not_found` — resource does not exist',
    '- `rate_limited` — too many requests; see `Retry-After`', '',
    '## Server Errors',
    '- `internal_error` — unexpected failure, safe to retry',
    '- `unavailable` — dependency down; retry with backoff',
  ].join('\n'),
  milestones: [
    '---', 'tags: [product, roadmap]', '---',
    '# Q3 Milestones', '',
    'Delivery checkpoints for the [[Roadmap Q3]] initiatives.', '',
    '## July',
    '- [x] Multi-region design sign-off',
    '- [ ] Failover prototype in staging', '',
    '## August',
    '- [ ] v1 deprecation notice published',
    '- [ ] Usage dashboard beta', '',
    '## September',
    '- [ ] Data residency controls GA',
    '- [ ] Multi-region default for new projects',
  ].join('\n'),
};

export const history: Record<string, HistorySnapshot[]> = {
  api: [
    { ts: 'Jun 28, 09:14', text: ['---', 'tags: [api, guidelines]', 'status: draft', '---', '# API Design Guidelines', '', '## Versioning', 'All public endpoints are versioned via the URL path. Breaking changes require a new major version.', '', '```http', 'GET /api/v2/users/:id', '```', '', '## Conventions', '- Use plural, lowercase resource names (`/invoices`)', '- Return ISO-8601 timestamps in UTC', '', '## Error Format', 'Errors return a consistent envelope with `code`, `message`, and an optional `details` object.'].join('\n') },
    { ts: 'Jun 27, 16:02', text: ['# API Design Guidelines', '', '## Versioning', 'Endpoints are versioned via the URL path.', '', '## Conventions', '- Use plural resource names', '- Timestamps in UTC'].join('\n') },
  ],
};

export const eml: Record<string, EmlData> = {
  q2: { from: 'platform@acme.dev', to: 'engineering-all@acme.dev', subject: 'Q2 Engineering Status Report', body: ['<h2 style="font:600 20px -apple-system,system-ui;color:#26241f;margin:0 0 14px">Q2 Engineering Status</h2>', '<p style="font:400 14px/1.7 -apple-system,system-ui;color:#403d37;margin:0 0 14px">Team — here is the automated Q2 summary, generated from this quarter’s shipping data.</p>', '<h3 style="font:600 15px -apple-system,system-ui;color:#26241f;margin:0 0 8px">Highlights</h3>', '<ul style="font:400 14px/1.7 -apple-system,system-ui;color:#403d37;margin:0 0 16px;padding-left:20px"><li>Shipped the v2 public API</li><li>Cut p95 latency by 38%</li><li>Migrated 12 services to the event bus</li></ul>', '<h3 style="font:600 15px -apple-system,system-ui;color:#26241f;margin:0 0 8px">Next Quarter</h3>', '<p style="font:400 14px/1.7 -apple-system,system-ui;color:#403d37;margin:0 0 18px">Focus on multi-region failover and the deprecation of v1 endpoints.</p>', '<p style="font:400 14px -apple-system,system-ui;color:#8a8a8f;margin:0">— The Platform Team</p>'].join('\n') },
  digest: { from: 'digest@acme.dev', to: 'team@acme.dev', subject: 'Weekly Engineering Digest', body: ['<h2 style="font:600 20px -apple-system,system-ui;color:#26241f;margin:0 0 14px">This Week in Engineering</h2>', '<ul style="font:400 14px/1.7 -apple-system,system-ui;color:#403d37;margin:0;padding-left:20px"><li>3 PRs merged to the API gateway</li><li>Incident #284 resolved</li><li>New onboarding doc published</li></ul>'].join('\n') },
  welcome: { from: 'hello@acme.dev', to: '{{customer.email}}', subject: 'Welcome to Acme Cloud', body: ['<h2 style="font:600 20px -apple-system,system-ui;color:#26241f;margin:0 0 14px">You’re in 🎉</h2>', '<p style="font:400 14px/1.7 -apple-system,system-ui;color:#403d37;margin:0 0 14px">Thanks for signing up. Your first deploy is one command away.</p>', '<pre style="font:13px ui-monospace,Menlo,monospace;background:#faf8f3;border:1px solid #eee;border-radius:8px;padding:12px 14px;margin:0 0 16px">npx acme deploy</pre>', '<p style="font:400 14px/1.7 -apple-system,system-ui;color:#403d37;margin:0">Questions? Just reply to this email.</p>'].join('\n') },
};

export const backlinkMap: Record<string, Backlink[]> = {
  api: [
    { id: 'runbook', title: 'Deployment Runbook', snippet: '…follows the API Design Guidelines for versioned releases…' },
    { id: 'adr', title: 'ADR-014 Event Bus', snippet: '…per the API Design Guidelines, v2 endpoints publish…' },
  ],
};

export const badgeColors: Record<string, { c: string; b: string }> = {
  md: { c: '#6c7686', b: 'rgba(108,118,134,.14)' },
  html: { c: '#b5651d', b: 'rgba(181,101,29,.14)' },
  eml: { c: '#3a6ea5', b: 'rgba(58,110,165,.14)' },
  pdf: { c: '#b3382c', b: 'rgba(179,56,44,.14)' },
};

export const typeLabels: Record<string, string> = {
  md: 'Markdown', html: 'HTML', eml: 'Outlook Template', pdf: 'PDF',
};

export interface SlashDef { label: string; hint: string; ins: string; }
export const slashDefs: SlashDef[] = [
  { label: 'Heading', hint: '##', ins: '## ' },
  { label: 'Bullet list', hint: '-', ins: '- ' },
  { label: 'Numbered list', hint: '1.', ins: '1. ' },
  { label: 'Task', hint: '[ ]', ins: '- [ ] ' },
  { label: 'Code block', hint: '```', ins: '```\n\n```' },
  { label: 'Quote', hint: '>', ins: '> ' },
  { label: 'Table', hint: '⊞', ins: '| Column A | Column B |\n| --- | --- |\n|  |  |' },
];

export function seedEditedAt(): Record<string, number> {
  const now = Date.now(), MIN = 60000, HR = 3600000, DAY = 86400000;
  return {
    api: now - 7 * MIN, postmortem: now - 22 * MIN, q2: now - 38 * MIN, security: now - 95 * MIN,
    roadmap: now - 2 * HR, runbook: now - 3 * HR, pricing: now - 8 * HR, oncall: now - 19 * HR,
    landing: now - 26 * HR, adr: now - 2 * DAY, welcome: now - 3 * DAY, digest: now - 4 * DAY,
  };
}
